points1=k4a3d('C:\\MATLAB\\K4A\\OFFICE_SAMPLE_NFOV_UNBINNED.mkv');
figure;
pcshow(pointCloud(points1'));
title('Near FOV unbinned');
xlabel('X');
ylabel('Y');
zlabel('Z');
points2=k4a3d('C:\\MATLAB\\K4A\\OFFICE_SAMPLE_NFOV_2x2BINNED.mkv');
figure;
pcshow(pointCloud(points2'));
title('Near FOV 2x2binned');
xlabel('X');
ylabel('Y');
zlabel('Z');
points3=k4a3d('C:\\MATLAB\\K4A\\OFFICE_SAMPLE_WFOV_UNBINNED.mkv');
figure;
pcshow(pointCloud(points3'));
title('Wide FOV unbinned');
xlabel('X');
ylabel('Y');
zlabel('Z');
points4=k4a3d('C:\\MATLAB\\K4A\\OFFICE_SAMPLE_WFOV_2x2BINNED.mkv');
figure;
pcshow(pointCloud(points4'));
title('Wide FOV 2x2binned');
xlabel('X');
ylabel('Y');
zlabel('Z');